{{- with .Values.persistence.media }}
{{- if .create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .claim }}
spec:
  accessModes:
    -  {{ .accessMode }}
  resources:
    requests:
      storage: {{ .storage }}
  {{- if .classname }}
  storageClassName: {{ .classname }}
  {{- end }}
{{- end }}
{{- end }}
