apiVersion: v1
kind: PersistentVolume
metadata:
  name: pms-downloads
  labels:
    storage: plexdownloads
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.50.1.50
    path: /kube/plexdownloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
  selector:
    matchLabels:
      storage: plexdownloads
  storageClassName: ""
