name: organizer
port: 80

image:
  repository: organizrtools/organizr-v2
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: "organizr.arturonet.com"

config:
  name: organizr-config


persistence:
  config:
    create: false
    claim: organizr
