# Default values for plexserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: pms
port: 32400
config: pms-config

image:
  repository: plexinc/pms-docker
  tag: latest

persistence:
  config:
    create: false
    claim: pms-config
    storage: 20Gi
    accessMode: ReadWriteOnce
  media:
    create: false
    claim: pms-media
    storage: 100Ti
    accessMode: ReadWriteMany
  transcode:
    create: true
    claim: pms-transcode
    storage: 10Gi
    accessMode: ReadWriteOnce
